//auth types
export const USER_IN_SESSION = 'GET_EMPLOYEE_IN_SESSION';
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const ERROR_LOGIN = 'ERROR_LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOADING = 'LOADING';
export const MESSAGE = 'MESSAGE';

//foundation types
export const GET_FOUNDATION = 'GET_FOUNDATION';
export const UPDATE_FOUNDATION_DATA = 'UPDATE_FOUNDATION_DATA';
export const TOGGLE_FOUNDATION_LOADING = 'TOGGLE_FOUNDATION_LOADING';
export const FOUNDATION_MESSAGE = 'FOUNDATION_MESSAGE';

//employee types
export const EMPLOYEES = 'EMPLOYEES';
export const SELECT_EMPLOYEE = 'SELECT_EMPLOYEE';
export const TOGGLE_EMPLOYEES_LOADING = 'TOGGLE_EMPLOYEES_LOADING';
export const EMPLOYEE_MESSAGE = 'EMPLOYEE_MESSAGE';
export const SUCCESS_PROFILE_UPDATE = 'SUCCESS_PROFILE_UPDATE';

// export const SHOW_MESSAGE = 'EMPLOYEES';

//post types
export const POSTS = 'POSTS';
export const SELECT_POST = 'SELECT_POST';
export const TOGGLE_POSTS_LOADING = 'TOGGLE_POSTS_LOADING';
export const POST_MESSAGE = 'POST_MESSAGE';
// export const SHOW_MESSAGE = 'POSTS';

//adopter types
export const ADOPTERS = 'ADOPTERS';
export const SELECT_ADOPTER = 'SELECT_ADOPTER';
export const TOGGLE_ADOPTER_LOADING = 'TOGGLE_ADOPTER_LOADING';
export const ADOPTER_MESSAGE = 'ADOPTER_MESSAGE';


//adoption types
export const ADOPTIONS = 'ADOPTIONS';
export const SELECT_ADOPTION = 'SELECT_ADOPTION';
export const TOGGLE_ADOPTION_LOADING = 'TOGGLE_ADOPTION_LOADING';
export const ADOPTION_MESSAGE = 'ADOPTION_MESSAGE';

//animal types
export const ANIMALS = 'ANIMAL';
export const SELECT_ANIMAL = 'SELECT_ANIMAL';
export const TOGGLE_ANIMAL_LOADING = 'TOGGLE_ANIMAL_LOADING';
export const ANIMAL_MESSAGE = 'ANIMAL_MESSAGE';
export const FILTER = 'FILTER';


//question types
export const QUESTIONS = 'QUESTION';
export const SELECT_QUESTION = 'SELECT_QUESTION';
export const SELECT_QUESTION_EDIT = 'SELECT_QUESTION_EDIT';

export const UNSELECT_QUESTION = 'UNSELECT_QUESTION';
export const TOGGLE_QUESTION_LOADING = 'TOGGLE_QUESTION_LOADING';
export const QUESTION_MESSAGE = 'QUESTION_MESSAGE';

//tracking types
export const TRACKINGS = 'TRACKINGS';
export const SELECT_TRACKING = 'SELECT_TRACKING';
export const TOGGLE_TRACKING_LOADING = 'TOGGLE_TRACKING_LOADING';
export const TRACKING_MESSAGE = 'TRACKING_MESSAGE';

